descriptor-schema-version: "2.2"

info:
  name: iox_docker_flask_web
  description: "IOx DevCycle Demo web server service"
  version: "1.0"
  author-link: ""
  author-name: "Jock Reed"

app:

  cpuarch: "x86_64"
  type: docker
  resources:
    profile: custom
    cpu: 50
    memory: 100
    network:
      -
        interface-name: eth0
        ports:
          tcp:
            - 80

  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["python3 web_server.py"]